package io.eleven19.mill.interceptor.shim

/** Templates for generating platform-specific shim scripts. */
object ShimTemplate:

    /** Generate a Unix (bash) shim script for the given build tool.
      *
      * The script will:
      *   - download the mill-interceptor binary if not cached
      *   - forward all CLI arguments to `mill-interceptor intercept <tool> [args...]`
      *   - support environment variables for configuration
      */
    def unix(tool: BuildTool, version: String): String =
        s"""#!/usr/bin/env bash
           |set -e
           |
           |# ---- mill-interceptor shim for ${tool.toolName} ----
           |# Generated by mill-interceptor shim generate
           |# This script downloads and caches mill-interceptor, then forwards
           |# all arguments to: mill-interceptor intercept ${tool.interceptName} [args...]
           |
           |MILL_INTERCEPTOR_HOME="$${MILL_INTERCEPTOR_HOME:-$$HOME/.mill-interceptor}"
           |MILL_INTERCEPTOR_VERSION="$${MILL_INTERCEPTOR_VERSION:-$version}"
           |MILL_INTERCEPTOR_DOWNLOAD_URL="$${MILL_INTERCEPTOR_DOWNLOAD_URL:-https://github.com/eleven19/mill-interceptor/releases/download/v$$MILL_INTERCEPTOR_VERSION/mill-interceptor}"
           |MILL_INTERCEPTOR_OPTS="$${MILL_INTERCEPTOR_OPTS:-}"
           |MILL_INTERCEPTOR_DEBUG="$${MILL_INTERCEPTOR_DEBUG:-false}"
           |
           |CACHE_DIR="$$MILL_INTERCEPTOR_HOME/$$MILL_INTERCEPTOR_VERSION"
           |BINARY="$$CACHE_DIR/mill-interceptor"
           |
           |if [ "$$MILL_INTERCEPTOR_DEBUG" = "true" ]; then
           |    set -x
           |fi
           |
           |download_interceptor() {
           |    mkdir -p "$$CACHE_DIR"
           |    echo "Downloading mill-interceptor $$MILL_INTERCEPTOR_VERSION ..." >&2
           |    if command -v curl > /dev/null 2>&1; then
           |        curl -fL -o "$$BINARY" "$$MILL_INTERCEPTOR_DOWNLOAD_URL"
           |    elif command -v wget > /dev/null 2>&1; then
           |        wget -q -O "$$BINARY" "$$MILL_INTERCEPTOR_DOWNLOAD_URL"
           |    else
           |        echo "Error: curl or wget is required to download mill-interceptor" >&2
           |        exit 1
           |    fi
           |    chmod +x "$$BINARY"
           |}
           |
           |if [ ! -f "$$BINARY" ]; then
           |    download_interceptor
           |fi
           |
           |# shellcheck disable=SC2086
           |exec "$$BINARY" $$MILL_INTERCEPTOR_OPTS intercept ${tool.interceptName} "$$@"
           |""".stripMargin

    /** Generate a Windows (cmd) shim script for the given build tool. */
    def windows(tool: BuildTool, version: String): String =
        s"""@echo off
           |setlocal enabledelayedexpansion
           |
           |rem ---- mill-interceptor shim for ${tool.toolName} ----
           |rem Generated by mill-interceptor shim generate
           |rem This script downloads and caches mill-interceptor, then forwards
           |rem all arguments to: mill-interceptor intercept ${tool.interceptName} [args...]
           |
           |if "%MILL_INTERCEPTOR_HOME%"=="" set "MILL_INTERCEPTOR_HOME=%USERPROFILE%\\.mill-interceptor"
           |if "%MILL_INTERCEPTOR_VERSION%"=="" set "MILL_INTERCEPTOR_VERSION=$version"
           |if "%MILL_INTERCEPTOR_DOWNLOAD_URL%"=="" set "MILL_INTERCEPTOR_DOWNLOAD_URL=https://github.com/eleven19/mill-interceptor/releases/download/v%MILL_INTERCEPTOR_VERSION%/mill-interceptor.exe"
           |if "%MILL_INTERCEPTOR_OPTS%"=="" set "MILL_INTERCEPTOR_OPTS="
           |if "%MILL_INTERCEPTOR_DEBUG%"=="" set "MILL_INTERCEPTOR_DEBUG=false"
           |
           |set "CACHE_DIR=%MILL_INTERCEPTOR_HOME%\\%MILL_INTERCEPTOR_VERSION%"
           |set "BINARY=%CACHE_DIR%\\mill-interceptor.exe"
           |
           |if "%MILL_INTERCEPTOR_DEBUG%"=="true" echo on
           |
           |if not exist "%BINARY%" (
           |    if not exist "%CACHE_DIR%" mkdir "%CACHE_DIR%"
           |    echo Downloading mill-interceptor %MILL_INTERCEPTOR_VERSION% ... >&2
           |    powershell -Command "Invoke-WebRequest -Uri '%MILL_INTERCEPTOR_DOWNLOAD_URL%' -OutFile '%BINARY%'"
           |    if errorlevel 1 (
           |        echo Error: failed to download mill-interceptor >&2
           |        exit /b 1
           |    )
           |)
           |
           |"%BINARY%" %MILL_INTERCEPTOR_OPTS% intercept ${tool.interceptName} %*
           |""".stripMargin
end ShimTemplate
